### ISSUE TITLE
Add Spring Module

### ISSUE THREAD

**Issue by wmarttala-cook** [wmarttala-cook/ftMay2018#4]
# Feature Request

---

Add the Spring from the May 2018 FT class the the repo.

### Tasks
- [ ] Add a Spring Directory
- [ ] Inside the Spring Directory, add the Assessment, Assignments, and Notes directories
- [ ] Add notes from each day of the module into the Notes directory
- [ ] Add a directory for each assignment in the Assignments directory and then one for each student within each individual assignment directory
- [ ] Add a directory for each student in the Assessment directory and move each student's assessment code into their respective directory
