### ISSUE TITLE
Add Final Project Module

### ISSUE THREAD

**Issue by wmarttala-cook** [wmarttala-cook/ftMay2018#5]
# Feature Request

---

Add the Final Project from the May 2018 FT class the repo.

### Tasks
- [ ] Add a Final Directory
- [ ] Inside the Final Directory, add a directory for each student
- [ ] Add each student's code to their respective directory
